# The "raw" packages will be installed first
preinstall:
  helm:
    - repo: https://metallb.github.io/metallb                                                           # MetalLB
      chart_ref: metallb/metallb
      name: metallb
      namespace: metallb-system
    - repo: https://charts.jetstack.io
      chart_ref: cert-manager/cert-manager
      namespace: cert-manager
      name: cert-manager
  raw:
    - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml                       # Tekton
    - https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml                       # Tekton Triggers
    - https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml                  # Tekton Trigger Interceptors
    - https://storage.googleapis.com/tekton-releases/dashboard/latest/tekton-dashboard-release.yaml     # Tekton Dashboard
    - https://github.com/tektoncd/catalog/raw/main/task/git-clone/0.6/git-clone.yaml                    # Tekton git-clone task
    - https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.crds.yaml      # Cert-manager CRDs
