apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github
  namespace: tekton-pipelines
spec:
  params:
  - name: gitref
    value: $(body.ref)
  - name: gitrevision
    value: $(body.after) # uses body from webhook payload
  - name: gitrepositoryname
    value: $(body.repository.name)
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)