apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: inventory-builder
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: source
    - name: inventory
      description: Compiled inventory from static data as well as Proxmox
  params:
    - name: proxmox_host_ip
      type: string
      description: Proxmox Host IP
    - name: proxmox_host_port
      type: string
      description: Proxmox Host API Port (usually 8006)
    - name: proxmox_user
      type: string
      description: User with which to access the Proxmox API
  steps:
    - name: build-inventory
      image: golang:alpine
      env:
        - name: PROXMOX_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: proxmox
              key: apiPassword
        - name: PROXMOX_API_HOST
          valueFrom:
            secretKeyRef:
              name: proxmox
              key: host
        - name: PROXMOX_API_PORT
          valueFrom:
            secretKeyRef:
              name: proxmox
              key: port
        - name: PROXMOX_API_USER
          valueFrom:
            secretKeyRef:
              name: proxmox
              key: user
      script: |
        #!/bin/sh
        go get github.com/rjcoupe/pm_inventory_builder
        $GOPATH/bin/pm_inventory_builder -url http://${PROXMOX_API_HOST}:${PROXMOX_API_PORT} -user ${PROXMOX_API_ROOT} > $(workspaces.inventory.path)/dynamic_inventory.yaml