apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: inventory_builder
spec:
  workspaces:
    - name: source
    - name: inventory
      description: Compiled inventory from static data as well as Proxmox
  params:
    - name: proxmox_host_ip
      type: string
      description: Proxmox Host IP
    - name: proxmox_host_port
      type: string
      description: Proxmox Host API Port (usually 8006)
    - name: proxmox_user
      type: string
      description: User with which to access the Proxmox API
  steps:
    - name: fetch_source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: github.com/rjcoupe/homelab
      workspaces:
        - name: output
          workspace: source
        - name: ssh-directory
          secret:
            secretName: ssh-credentials
    - name: build_inventory
      image: golang:alpine
      env:
        - name: PROXMOX_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: proxmox
              key: apiPassword
      script: |
        #!/bin/sh
        go get github.com/rjcoupe/pm_inventory_builder
        pm_inventory_builder -url http://$(params.proxmox_host_ip):$(params.proxmox_host_port) -user $(proxmox_user) > $(workspaces.inventory.path)/dynamic_inventory.yaml
    - name: combine_inventories
      image: node:alpine
      script: |
        npm install -g @alexlafroscia/yaml-merge
        statics=$(ls $(workspaces.source.path)/config/inventories.yaml)
        yaml-merge $(workspaces.inventory.path)/dynamic_inventory.yaml $statics > $(workspaces.inventory.path)/inventory.yaml
