apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: inventory-builder
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: source
  steps:
    - name: build-inventory
      image: golang:alpine
      env:
        - name: PM_API_TOKEN_ID
          valueFrom:
            secretKeyRef:
              name: proxmox
              key: tokenId
        - name: PM_API_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: proxmox
              key: tokenSecret
        - name: PM_API_HOST
          valueFrom:
            secretKeyRef:
              name: proxmox
              key: host
      script: |
        #!/bin/sh
        go install github.com/rjcoupe/pm_inventory_builder@latest
        $GOPATH/bin/pm_inventory_builder \
          -url https://${PM_API_HOST}:8006 \
          -tokenId ${PM_API_TOKEN_ID} \
          -tokenSecret ${PM_API_TOKEN_SECRET} \
          -allow-insecure-tls \
          > $(workspaces.source.path)/ansible/inventories/dynamic.yaml
        cat $(workspaces.source.path)/ansible/inventories/dynamic.yaml