all:
    hosts:
        master:
            ansible_host: 192.168.1.143
        worker-1:
            ansible_host: 192.168.1.144
kubernetes-master:
    hosts:
        master:
            ansible_host: 192.168.1.143
kubernetes-worker:
    hosts:
        worker-1:
            ansible_host: 192.168.1.144
ungrouped:
    hosts: {}

