apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: homelab
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: ssh-directory
      description: SSH credentials for git cloning
    - name: source
      description: Source cloned from git repo.
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: ssh-directory
          workspace: ssh-directory
        - name: output
          workspace: source
    - name: terraform
      runAfter: 
        - fetch-source
      taskRef:
        name: terraform-cli
      workspaces:
        - name: source
          workspace: source
      params:
        - name: ARGS
          value:
            - apply
            - "-auto-approve"
    - name: build-inventory
      runAfter:
        - terraform
      taskRef:
        name: inventory-builder
    # - name: ansible
    #   workspaces:
    #     - name: source
    #       workspace: source
    #     - name: inventory
    #       workspace: inventory
    #   runAfter:
    #     - build_inventory
      
