all:
  hosts:
    pi1:
      ansible_host: 192.168.1.12
      ansible_user: ubuntu # No, it doesn't have the default password any more

k3s_master:
  hosts:
    pi1:
      ansible_host: 192.168.1.12
      ansible_user: ubuntu # No, it doesn't have the default password any more