- name: Generate cluster join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['kubernetes-master'][0] }}"

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- name: Reset Kubeadm
  shell: kubeadm reset -f

- name: Join cluster
  shell: "{{ kubeadm_join }}"