apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-webhooks
  namespace: tekton-pipelines
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/clusterissuer: letsencrypt
spec:
  tls:
    - hosts:
      - ci.rjcoupe.dev
      secretName: ci-rjcoupe-dev-tls
  rules:
    - http:
        paths:
          - path: /hooks
            pathType: Exact
            backend:
              service:
                name: el-github-pr
                port:
                  number: 8080