- name: Get cluster join token
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_node_token
  delegate_to: "{{ groups['k3s_master'][0] }}"

- name: Install K3s on Worker
  command: curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_node_token }} K3S_URL=https://{{ hostvars['k3s_master'][0]['ansible_eth0']['ipv4']['address'] }}:6443 sh -